name: Auto Build EXE

on: 
  push:  # 任何分支的推送都会触
    branches-ignore: [ gh-pages ]  # 可选：忽略文档分支

jobs:
  build-exe:
    runs-on: windows-latest
    timeout-minutes: 15  # 防止卡死
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 配置Python环境
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # 固定Python版本

      - name: 安装依赖
        run: |
          pip install --upgrade pip
          pip install pyinstaller python-docx dashscope fuzzywuzzy openai

      - name: 构建可执行文件
        run: pyinstaller --onefile --noconsole VoiceGPT.py  # 去掉黑窗

      - name: 上传产物
        uses: actions/upload-artifact@v4
        with:
          name: AppExecutable
          path: dist/*.exe
          if-no-files-found: error  # 空构建时主动报错